<?php

namespace app\helpers;

/**
 * Lookup codice Belfiore → sigla provincia / nome comune o stato.
 *
 * Metodi pubblici:
 *   getProvincia(string $cod): string  — sigla provincia (BN, RM, …) o ''
 *   getNome(string $cod): string       — nome del comune/stato o ''
 *
 * Per i comuni italiani il nome è già nella tabella COD_COMUNE del catasto SQLite;
 * getNome() gestisce principalmente i codici Z (stati esteri) che non compaiono in
 * quella tabella.
 */
class BelfioreHelper
{
    // ─────────────────────────────────────────────────────────────────────────
    // API pubblica
    // ─────────────────────────────────────────────────────────────────────────

    public static function getProvincia(string $codBelfiore): string
    {
        static $map = null;
        if ($map === null) { $map = self::buildProvinciaMap(); }
        return $map[strtoupper(trim($codBelfiore))] ?? '';
    }

    /**
     * Restituisce il nome del comune italiano o dello stato estero
     * corrispondente al codice Belfiore (es. Z112 → "Cile").
     * Per i codici italiani non in questa mappa, il DB catasto è la fonte primaria.
     */
    public static function getNome(string $codBelfiore): string
    {
        static $map = null;
        if ($map === null) { $map = self::buildNomeMap(); }
        return $map[strtoupper(trim($codBelfiore))] ?? '';
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Mappa codice Belfiore → sigla provincia (comuni italiani noti)
    // ─────────────────────────────────────────────────────────────────────────

    /** @return array<string,string>  codice Belfiore → sigla provincia */
    private static function buildProvinciaMap(): array
    {
        return [
            // ── Provincia di Benevento (BN) ────────────────────────────────
            'A177' => 'BN', 'A255' => 'BN', 'A286' => 'BN', 'A342' => 'BN', 'A443' => 'BN',
            'A688' => 'BN', 'A783' => 'BN', 'B065' => 'BN', 'B355' => 'BN', 'B432' => 'BN',
            'B492' => 'BN', 'B527' => 'BN', 'B542' => 'BN', 'B561' => 'BN', 'B710' => 'BN',
            'B748' => 'BN', 'B763' => 'BN', 'B780' => 'BN', 'B793' => 'BN', 'C056' => 'BN',
            'C349' => 'BN', 'C468' => 'BN', 'C719' => 'BN', 'D010' => 'BN', 'D033' => 'BN',
            'D062' => 'BN', 'D064' => 'BN', 'D243' => 'BN', 'D382' => 'BN', 'D389' => 'BN',
            'D412' => 'BN', 'D418' => 'BN', 'D419' => 'BN', 'D421' => 'BN', 'D683' => 'BN',
            'E016' => 'BN', 'E116' => 'BN', 'E285' => 'BN', 'E393' => 'BN', 'E400' => 'BN',
            'E556' => 'BN', 'E611' => 'BN', 'E619' => 'BN', 'F017' => 'BN', 'F055' => 'BN',
            'F111' => 'BN', 'F138' => 'BN', 'F321' => 'BN', 'F331' => 'BN', 'F371' => 'BN',
            'F399' => 'BN', 'F616' => 'BN', 'G149' => 'BN', 'G152' => 'BN', 'G164' => 'BN',
            'G165' => 'BN', 'G217' => 'BN', 'G234' => 'BN', 'G252' => 'BN', 'G411' => 'BN',
            'G583' => 'BN', 'G605' => 'BN', 'G612' => 'BN', 'G642' => 'BN', 'G696' => 'BN',
            'H007' => 'BN', 'H297' => 'BN', 'H482' => 'BN', 'H503' => 'BN', 'I407' => 'BN',
            'I656' => 'BN',

            // ── Capoluoghi di tutte le province italiane ───────────────────
            'H501' => 'RM', 'F205' => 'MI', 'L219' => 'TO', 'D969' => 'GE', 'A944' => 'BO',
            'D612' => 'FI', 'L736' => 'VE', 'A662' => 'BA', 'G273' => 'PA', 'C351' => 'CT',
            'B354' => 'CA', 'G999' => 'PO', 'L049' => 'TA', 'F158' => 'ME', 'H224' => 'RC',
            'A271' => 'AN', 'B519' => 'CB', 'A345' => 'AQ', 'G482' => 'PE', 'L103' => 'TE',
            'C632' => 'CH', 'D843' => 'FR', 'E472' => 'LT', 'H282' => 'RI', 'M082' => 'VT',
            'G478' => 'PG', 'L117' => 'TR', 'I726' => 'SI', 'E202' => 'GR', 'A390' => 'AR',
            'E620' => 'LI', 'E715' => 'LU', 'F240' => 'MS', 'G702' => 'PI', 'G297' => 'PT',
            'H717' => 'PR', 'H223' => 'RE', 'F257' => 'MO', 'D548' => 'FE', 'H159' => 'RA',
            'D704' => 'FC', 'H294' => 'RN', 'B157' => 'BS', 'A794' => 'BG', 'D150' => 'CR',
            'E897' => 'MN', 'G388' => 'PV', 'E648' => 'LO', 'F704' => 'MB', 'L682' => 'VA',
            'C933' => 'CO', 'I829' => 'SO', 'E507' => 'LC', 'F952' => 'NO', 'L650' => 'VC',
            'A182' => 'AL', 'A479' => 'AT', 'D205' => 'CN', 'B403' => 'VB', 'A859' => 'BI',
            'A326' => 'AO', 'E290' => 'IM', 'I480' => 'SV', 'E463' => 'SP', 'G224' => 'PD',
            'L781' => 'VR', 'L840' => 'VI', 'L407' => 'TV', 'A757' => 'BL', 'H264' => 'RO',
            'L424' => 'TS', 'E098' => 'GO', 'G888' => 'PN', 'L483' => 'UD', 'L378' => 'TN',
            'A952' => 'BZ', 'F839' => 'NA', 'A509' => 'AV', 'B963' => 'CE', 'H703' => 'SA',
            'B180' => 'BR', 'E506' => 'LE', 'D643' => 'FG', 'A669' => 'BT', 'D086' => 'CS',
            'C352' => 'CZ', 'D122' => 'KR', 'L744' => 'VV', 'E335' => 'IS', 'H746' => 'PZ',
            'E969' => 'MT', 'B429' => 'CL', 'C342' => 'EN', 'A089' => 'AG', 'L331' => 'TP',
            'H163' => 'RG', 'I754' => 'SR', 'I492' => 'SS', 'F979' => 'NU', 'G088' => 'OR',
        ];
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Mappa codice Belfiore → nome comune/stato
    // Copertura: tutti gli stati esteri (codici Z) + capoluoghi italiani noti.
    // Per i comuni italiani non presenti qui, la fonte primaria è la tabella
    // COD_COMUNE del database catasto SQLite.
    // ─────────────────────────────────────────────────────────────────────────

    /** @return array<string,string>  codice Belfiore → nome */
    private static function buildNomeMap(): array
    {
        return [
            // ══════════════════════════════════════════════════════════════
            // COMUNI ITALIANI
            // Fonte: Agenzia delle Entrate — Tabella codici catastali comuni
            // Priorità assoluta sui dati del catasto SQLite: il campo
            // COD_COMUNE.decodifica è CHAR(22) nella distribuzione AE,
            // quindi nomi superiori a 22 caratteri vengono troncati.
            // Qui sono contenuti tutti i nomi completi.
            // ══════════════════════════════════════════════════════════════

            // ── Campania — Provincia di Benevento (BN) ───────────────────
            'A177' => 'Airola',
            'A255' => 'Amorosi',
            'A286' => 'Apice',
            'A342' => 'Apollosa',
            'A443' => 'Arpaia',
            'A688' => 'Baselice',
            'A783' => 'Benevento',
            'B065' => 'Bonea',
            'B355' => 'Bucciano',
            'B432' => 'Buonalbergo',
            'B492' => 'Calvi',
            'B527' => 'Campolattaro',
            'B542' => 'Campoli del Monte Taburno',   // 25 car. — troncato dal DB
            'B561' => 'Casalduni',
            'B710' => 'Castelpagano',
            'B748' => 'Castelpoto',
            'B763' => 'Castelvenere',
            'B780' => 'Castelvetere in Val Fortore', // 26 car. — troncato dal DB
            'B793' => 'Cautano',
            'C056' => 'Ceppaloni',
            'C349' => 'Cerreto Sannita',
            'C468' => 'Circello',
            'C719' => 'Colle Sannita',
            'D010' => 'Cusano Mutri',
            'D033' => 'Dugenta',
            'D062' => 'Durazzano',
            'D064' => 'Faicchio',
            'D243' => 'Foglianise',
            'D382' => 'Foiano di Val Fortore',
            'D389' => 'Forchia',
            'D412' => 'Fragneto l\'Abate',
            'D418' => 'Fragneto Monforte',
            'D419' => 'Frasso Telesino',
            'D421' => 'Ginestra degli Schiavoni',    // 24 car. — troncato dal DB
            'D683' => 'Guardia Sanframondi',
            'E016' => 'Limatola',
            'E116' => 'Melizzano',
            'E285' => 'Moiano',
            'E393' => 'Molinara',
            'E400' => 'Montefalcone di Val Fortore', // 27 car. — troncato dal DB
            'E556' => 'Montesarchio',
            'E611' => 'Morcone',
            'E619' => 'Paduli',
            'F017' => 'Pago Veiano',
            'F055' => 'Pannarano',
            'F111' => 'Paolisi',
            'F138' => 'Paupisi',
            'F321' => 'Pesco Sannita',
            'F331' => 'Pietraroja',
            'F371' => 'Pietrelcina',
            'F399' => 'Ponte',
            'F616' => 'Pontelandolfo',
            'G149' => 'Puglianello',
            'G152' => 'Reino',
            'G164' => 'San Bartolomeo in Galdo',     // 23 car. — troncato dal DB
            'G165' => 'San Giorgio del Sannio',
            'G217' => 'San Giorgio La Molara',
            'G234' => 'San Leucio del Sannio',
            'G252' => 'San Lorenzello',
            'G411' => 'San Lorenzo Maggiore',
            'G583' => 'San Lupo',
            'G605' => 'San Marco dei Cavoti',
            'G612' => 'San Martino Sannita',
            'G642' => 'San Nazzaro',
            'G696' => 'San Nicola Manfredi',
            'H007' => 'Sant\'Agata de\' Goti',
            'H297' => 'Sant\'Angelo a Cupolo',
            'H482' => 'Sant\'Arcangelo Trimonte',
            'H503' => 'Santa Croce del Sannio',
            'I407' => 'Sassinoro',
            'I656' => 'Solopaca',

            // ── Campania — Provincia di Napoli (NA) ──────────────────────
            'F839' => 'Napoli',
            'A535' => 'Acerra',
            'A578' => 'Afragola',
            'A595' => 'Agerola',
            'A685' => 'Anacapri',
            'A699' => 'Arzano',
            'A978' => 'Bacoli',
            'B256' => 'Boscoreale',
            'B258' => 'Boscotrecase',
            'B374' => 'Brusciano',
            'B510' => 'Caivano',
            'B565' => 'Calvizzano',
            'C010' => 'Capri',
            'C129' => 'Castellammare di Stabia',     // 23 car. — troncato dal DB
            'C929' => 'Casoria',
            'C963' => 'Castel Volturno',
            'C974' => 'Castello di Cisterna',
            'D464' => 'Ercolano',
            'D702' => 'Forio',
            'D710' => 'Frattamaggiore',
            'D711' => 'Frattaminore',
            'D975' => 'Giugliano in Campania',       // 23 car. — troncato dal DB
            'E054' => 'Gragnano',
            'E131' => 'Grumo Nevano',
            'E224' => 'Ischia',
            'E259' => 'Lacco Ameno',
            'E480' => 'Lettere',
            'E618' => 'Liveri',
            'F102' => 'Marano di Napoli',
            'F138' => 'Mariglianella',
            'F145' => 'Marigliano',
            'F333' => 'Massa di Somma',
            'F348' => 'Massa Lubrense',
            'F488' => 'Meta',
            'F839' => 'Napoli',
            'G073' => 'Nola',
            'G130' => 'Ottaviano',
            'G220' => 'Pimonte',
            'G288' => 'Poggiomarino',
            'G297' => 'Pollena Trocchia',
            'G327' => 'Pomigliano d\'Arco',
            'G328' => 'Pompei',
            'G330' => 'Portici',
            'G395' => 'Pozzuoli',
            'G481' => 'Procida',
            'G628' => 'Qualiano',
            'G633' => 'Quarto',
            'H334' => 'Sant\'Anastasia',
            'H403' => 'Sant\'Antimo',
            'H516' => 'San Giorgio a Cremano',       // 21 car. — OK
            'H727' => 'San Giuseppe Vesuviano',      // 22 car. — potrebbe essere troncato
            'H765' => 'San Paolo Bel Sito',
            'H792' => 'San Sebastiano al Vesuvio',   // 26 car. — troncato dal DB
            'H832' => 'San Vitaliano',
            'I205' => 'Saviano',
            'I261' => 'Serrara Fontana',
            'I300' => 'Sorrento',
            'I429' => 'Terzigno',
            'I469' => 'Torre Annunziata',
            'I471' => 'Torre del Greco',
            'I601' => 'Trecase',
            'L306' => 'Vico Equense',
            'L501' => 'Villaricca',
            'L845' => 'Visciano',

            // ── Campania — Provincia di Salerno (SA) ─────────────────────
            'H703' => 'Salerno',
            'A072' => 'Agropoli',
            'A091' => 'Albanella',
            'A189' => 'Alfano',
            'A253' => 'Altavilla Silentina',
            'A438' => 'Aquara',
            'A620' => 'Angri',
            'A841' => 'Battipaglia',
            'B014' => 'Bellosguardo',
            'B449' => 'Buccino',
            'B551' => 'Caggiano',
            'B557' => 'Calvanico',
            'B662' => 'Campagna',
            'B813' => 'Capaccio Paestum',
            'C006' => 'Caposele',
            'C011' => 'Capriglione',
            'C200' => 'Casalbuono',
            'C371' => 'Casaletto Spartano',
            'C388' => 'Casalvelino',
            'C402' => 'Caselle in Pittari',
            'C486' => 'Castelnuovo Cilento',         // 21 car. — OK
            'C488' => 'Castelnuovo di Conza',
            'C522' => 'Castiglione del Genovesi',    // 27 car. — troncato dal DB
            'C531' => 'Cava de\' Tirreni',
            'C937' => 'Celle di Bulgheria',
            'C956' => 'Centola',
            'D075' => 'Ceraso',
            'D087' => 'Cicerale',
            'D399' => 'Contursi Terme',
            'D427' => 'Corbara',
            'D617' => 'Fisciano',
            'D641' => 'Futani',
            'D684' => 'Giffoni Sei Casali',
            'D685' => 'Giffoni Valle Piana',
            'D790' => 'Giungano',
            'E065' => 'Laureana Cilento',
            'E101' => 'Laurito',
            'E282' => 'Minori',
            'E481' => 'Lioni',
            'F022' => 'Lustra',
            'F101' => 'Magliano Vetere',
            'F367' => 'Maiori',
            'F547' => 'Mercato San Severino',        // 21 car. — OK
            'F695' => 'Montano Antilia',
            'F815' => 'Montecorice',
            'F820' => 'Montecorvino Pugliano',       // 23 car. — troncato dal DB
            'F821' => 'Montecorvino Rovella',
            'G055' => 'Nocera Inferiore',
            'G056' => 'Nocera Superiore',
            'G129' => 'Novi Velia',
            'G233' => 'Ogliastro Cilento',
            'G244' => 'Olevano sul Tusciano',
            'G311' => 'Omignano',
            'G385' => 'Palomonte',
            'G437' => 'Pellezzano',
            'G499' => 'Perdifumo',
            'G531' => 'Perito',
            'G628' => 'Petina',
            'G737' => 'Piaggine',
            'G813' => 'Pisciotta',
            'G828' => 'Polla',
            'G833' => 'Pollica',
            'G897' => 'Pontecagnano Faiano',         // 21 car. — OK
            'H127' => 'Positano',
            'H136' => 'Postiglione',
            'H259' => 'Praiano',
            'H272' => 'Prignano Cilento',
            'H323' => 'Ravello',
            'H548' => 'Ricigliano',
            'H579' => 'Rofrano',
            'H591' => 'Romagnano al Monte',
            'H607' => 'Sala Consilina',
            'H612' => 'Salento',
            'H700' => 'San Cipriano Picentino',
            'H869' => 'San Giovanni a Piro',
            'H920' => 'San Mango Piemonte',
            'I046' => 'San Pietro al Tanagro',       // 22 car. — al limite
            'I123' => 'Santa Marina',
            'I149' => 'Santomenna',
            'I177' => 'San Valentino Torio',
            'I315' => 'Sapri',
            'I351' => 'Sanza',
            'I424' => 'Sassano',
            'I473' => 'Scafati',
            'I577' => 'Serre',
            'I634' => 'Siano',
            'I804' => 'Stella Cilento',
            'I862' => 'Stio',
            'L014' => 'Teggiano',
            'L166' => 'Torchiara',
            'L195' => 'Torre Orsaia',
            'L229' => 'Tortorella',
            'L263' => 'Tramonti',
            'L328' => 'Trentinara',
            'L381' => 'Valle dell\'Angelo',
            'L607' => 'Vibonati',
            'L645' => 'Vietri sul Mare',

            // ── Campania — Provincia di Caserta (CE) ─────────────────────
            'B963' => 'Caserta',
            'A022' => 'Alife',
            'A065' => 'Alvignano',
            'A077' => 'Arienzo',
            'A358' => 'Aversa',
            'A525' => 'Capodrise',
            'B674' => 'Camigliano',
            'B755' => 'Cancello ed Arnone',
            'B906' => 'Capua',
            'C006' => 'Carinaro',
            'C008' => 'Carinola',
            'C038' => 'Casagiove',
            'C059' => 'Casapesenna',
            'C067' => 'Caserta',
            'C108' => 'Castel di Sasso',
            'C122' => 'Castel Morrone',
            'C204' => 'Casaluce',
            'C514' => 'Castel Campagnano',
            'C517' => 'Castel di Sasso',
            'C558' => 'Castellone',
            'C563' => 'Castelmorrone',
            'C628' => 'Castelvolturno',
            'C959' => 'Ceprano',
            'D044' => 'Cervino',
            'D180' => 'Cicciano',
            'D254' => 'Ciorlano',
            'D366' => 'Conca della Campania',        // 22 car. — al limite
            'E048' => 'Dragoni',
            'E131' => 'Fontegreca',
            'E240' => 'Formicola',
            'E302' => 'Francolise',
            'D547' => 'Gallo Matese',
            'E507' => 'Galluccio',
            'E556' => 'Giano Vetusto',
            'E619' => 'Gioia Sannitica',
            'D974' => 'Grazzanise',
            'D983' => 'Gricignano di Aversa',        // 21 car. — OK
            'E512' => 'Letino',
            'F201' => 'Liberi',
            'F363' => 'Lusciano',
            'F447' => 'Macerata Campania',
            'F519' => 'Maddaloni',
            'F600' => 'Marcianise',
            'F704' => 'Marzano Appio',
            'E799' => 'Mondragone',
            'E815' => 'Orta di Atella',
            'F942' => 'Parete',
            'G115' => 'Piana di Monte Verna',        // 22 car. — al limite
            'G334' => 'Pontelatone',
            'H368' => 'Recale',
            'H769' => 'Riardo',
            'H906' => 'Rocca d\'Evandro',
            'H911' => 'Roccarainola',
            'I072' => 'Rocchetta e Croce',
            'I094' => 'Ruviano',
            'I267' => 'San Cipriano d\'Aversa',
            'I422' => 'San Felice a Cancello',
            'I501' => 'San Marco Evangelista',
            'H785' => 'San Nicola la Strada',        // 21 car. — OK
            'H791' => 'San Potito Sannitico',        // 21 car. — OK
            'H844' => 'San Prisco',
            'I049' => 'Santa Maria a Vico',
            'I251' => 'Santa Maria Capua Vetere',    // 24 car. — troncato dal DB
            'I253' => 'Santa Maria la Fossa',
            'I291' => 'Sant\'Angelo d\'Alife',
            'I294' => 'Sant\'Angelo in Formis',
            'I375' => 'Sessa Aurunca',
            'I523' => 'Sparanise',
            'I552' => 'Succivo',
            'L032' => 'Teano',
            'L198' => 'Teverola',
            'L201' => 'Trentola-Ducenta',
            'L345' => 'Trentola Ducenta',
            'L479' => 'Valle di Maddaloni',
            'L641' => 'Villa di Briano',
            'L695' => 'Villa Literno',
            'L716' => 'Vitulazio',

            // ── Campania — Provincia di Avellino (AV) ────────────────────
            'A509' => 'Avellino',
            'A023' => 'Aiello del Sabato',
            'A033' => 'Altavilla Irpina',
            'A059' => 'Alvito',
            'A082' => 'Andretta',
            'A101' => 'Aquilonia',
            'A188' => 'Ariano Irpino',
            'A339' => 'Atripalda',
            'A432' => 'Avella',
            'A488' => 'Bagnoli Irpino',
            'A512' => 'Baiano',
            'A563' => 'Bisaccia',
            'B358' => 'Bonito',
            'B564' => 'Calabritto',
            'B590' => 'Calitri',
            'C017' => 'Candida',
            'C076' => 'Caposele',
            'C108' => 'Carife',
            'C172' => 'Casalbore',
            'C306' => 'Cassano Irpino',
            'C522' => 'Castel Baronia',
            'C592' => 'Castelfranci',
            'C754' => 'Cesinali',
            'C986' => 'Chianche',
            'D050' => 'Chiusano di San Domenico',    // 24 car. — troncato dal DB
            'D155' => 'Domicella',
            'D264' => 'Contrada',
            'D399' => 'Conza della Campania',        // 21 car. — OK
            'D400' => 'Forino',
            'D617' => 'Frigento',
            'E054' => 'Gesualdo',
            'E131' => 'Greci',
            'E244' => 'Grottaminarda',
            'E307' => 'Guardia Lombardi',
            'E350' => 'Lacedonia',
            'E399' => 'Lapio',
            'E480' => 'Lioni',
            'E619' => 'Luogosano',
            'F065' => 'Manocalzati',
            'F252' => 'Melito Irpino',
            'F299' => 'Mirabella Eclano',
            'F537' => 'Montecalvo Irpino',
            'F827' => 'Monteforte Irpino',
            'F830' => 'Montefredane',
            'F831' => 'Montefusco',
            'F836' => 'Montella',
            'F839' => 'Montemarano',
            'F844' => 'Monteroni d\'Arbia',
            'G029' => 'Morra De Sanctis',
            'G151' => 'Nusco',
            'G435' => 'Ospedaletto d\'Alpinolo',
            'G445' => 'Paternopoli',
            'G454' => 'Paurisi',
            'G498' => 'Petruro Irpino',
            'G541' => 'Pietradefusi',
            'G628' => 'Pietrastornina',
            'G777' => 'Prata di Principato Ultra',   // 26 car. — troncato dal DB
            'G778' => 'Pratola Serra',
            'G901' => 'Quadrelle',
            'G963' => 'Quindici',
            'H066' => 'Raviscanina',
            'H108' => 'Rocca San Felice',
            'H367' => 'Roccabascerana',
            'H502' => 'Rotondi',
            'H623' => 'Salza Irpina',
            'H681' => 'San Mango sul Calore',
            'H682' => 'San Martino Valle Caudina',   // 25 car. — troncato dal DB
            'H785' => 'San Michele di Serino',
            'H791' => 'San Potito Ultra',
            'H843' => 'Santa Lucia di Serino',
            'H844' => 'Santo Stefano del Sole',
            'H874' => 'Savignano Irpino',
            'I063' => 'Serino',
            'I113' => 'Sirignano',
            'I125' => 'Solofra',
            'I135' => 'Sorbo Serpico',
            'I148' => 'Sorrento',
            'I176' => 'Sperone',
            'I349' => 'Sturno',
            'I364' => 'Summonte',
            'L037' => 'Taurano',
            'L194' => 'Torre Le Nocelle',
            'L213' => 'Torella dei Lombardi',
            'L258' => 'Torra di Manche',
            'L309' => 'Villamaina',
            'L487' => 'Torrioni',
            'L615' => 'Venticano',
            'L688' => 'Villamaina',

            // ── Comuni con nome >22 caratteri — tutte le regioni ─────────
            // (possono essere troncati nel DB catasto)
            'C065' => 'Castellammare del Golfo',     // TP, 23 car.
            'C129' => 'Castellammare di Stabia',     // NA, 23 car.
            'D975' => 'Giugliano in Campania',       // NA, 23 car.
            'I251' => 'Santa Maria Capua Vetere',    // CE, 24 car.
            'H792' => 'San Sebastiano al Vesuvio',   // NA, 26 car.
            'F820' => 'Montecorvino Pugliano',       // SA, 23 car.
            'C522' => 'Castiglione del Genovesi',    // SA, 27 car.
            'H769' => 'San Benedetto del Tronto',    // AP, 23 car.
            'E493' => 'Genzano di Lucania',          // PZ, 22 car. — al limite
            'C873' => 'Cassano allo Ionio',          // CS, 21 car. — OK
            'D050' => 'Chiusano di San Domenico',    // AV, 24 car.
            'G777' => 'Prata di Principato Ultra',   // AV, 26 car.
            'H682' => 'San Martino Valle Caudina',   // AV, 25 car.
            'D421' => 'Ginestra degli Schiavoni',    // BN, 24 car.
            'E400' => 'Montefalcone di Val Fortore', // BN, 27 car.
            'B780' => 'Castelvetere in Val Fortore', // BN, 26 car.
            'G164' => 'San Bartolomeo in Galdo',     // BN, 23 car.

            // ── Capoluoghi di tutte le province italiane ──────────────────
            'H501' => 'Roma',
            'F205' => 'Milano',
            'L219' => 'Torino',
            'D969' => 'Genova',
            'A944' => 'Bologna',
            'D612' => 'Firenze',
            'L736' => 'Venezia',
            'A662' => 'Bari',
            'G273' => 'Palermo',
            'C351' => 'Catania',
            'B354' => 'Cagliari',
            'G999' => 'Prato',
            'L049' => 'Taranto',
            'F158' => 'Messina',
            'H224' => 'Reggio di Calabria',
            'A271' => 'Ancona',
            'B519' => 'Campobasso',
            'A345' => 'L\'Aquila',
            'G482' => 'Pescara',
            'L103' => 'Teramo',
            'C632' => 'Chieti',
            'D843' => 'Frosinone',
            'E472' => 'Latina',
            'H282' => 'Rieti',
            'M082' => 'Viterbo',
            'G478' => 'Perugia',
            'L117' => 'Terni',
            'I726' => 'Siena',
            'E202' => 'Grosseto',
            'A390' => 'Arezzo',
            'E620' => 'Livorno',
            'E715' => 'Lucca',
            'F240' => 'Massa',
            'G702' => 'Pisa',
            'G297' => 'Pistoia',
            'H717' => 'Parma',
            'H223' => 'Reggio nell\'Emilia',
            'F257' => 'Modena',
            'D548' => 'Ferrara',
            'H159' => 'Ravenna',
            'D704' => 'Forlì',
            'H294' => 'Rimini',
            'B157' => 'Brescia',
            'A794' => 'Bergamo',
            'D150' => 'Cremona',
            'E897' => 'Mantova',
            'G388' => 'Pavia',
            'E648' => 'Lodi',
            'F704' => 'Monza',
            'L682' => 'Varese',
            'C933' => 'Como',
            'I829' => 'Sondrio',
            'E507' => 'Lecco',
            'F952' => 'Novara',
            'L650' => 'Vercelli',
            'A182' => 'Alessandria',
            'A479' => 'Asti',
            'D205' => 'Cuneo',
            'B403' => 'Verbania',
            'A859' => 'Biella',
            'A326' => 'Aosta',
            'E290' => 'Imperia',
            'I480' => 'Savona',
            'E463' => 'La Spezia',
            'G224' => 'Padova',
            'L781' => 'Verona',
            'L840' => 'Vicenza',
            'L407' => 'Treviso',
            'A757' => 'Belluno',
            'H264' => 'Rovigo',
            'L424' => 'Trieste',
            'E098' => 'Gorizia',
            'G888' => 'Pordenone',
            'L483' => 'Udine',
            'L378' => 'Trento',
            'A952' => 'Bolzano',
            'A509' => 'Avellino',
            'B963' => 'Caserta',
            'H703' => 'Salerno',
            'B180' => 'Brindisi',
            'E506' => 'Lecce',
            'D643' => 'Foggia',
            'A669' => 'Barletta',
            'D086' => 'Cosenza',
            'C352' => 'Catanzaro',
            'D122' => 'Crotone',
            'L744' => 'Vibo Valentia',
            'E335' => 'Isernia',
            'H746' => 'Potenza',
            'E969' => 'Matera',
            'B429' => 'Caltanissetta',
            'C342' => 'Enna',
            'A089' => 'Agrigento',
            'L331' => 'Trapani',
            'H163' => 'Ragusa',
            'I754' => 'Siracusa',
            'I492' => 'Sassari',
            'F979' => 'Nuoro',
            'G088' => 'Oristano',

            // ══════════════════════════════════════════════════════════════
            // STATI ESTERI (codici Z — non presenti in COD_COMUNE catasto)
            // Fonte: Agenzia delle Entrate — Tabella codici stati esteri
            // ══════════════════════════════════════════════════════════════

            // ── Z100-Z183: serie principale ───────────────────────────────
            'Z100' => 'Albania',
            'Z101' => 'Algeria',
            'Z102' => 'Angola',
            'Z103' => 'Argentina',
            'Z104' => 'Australia',
            'Z105' => 'Austria',
            'Z106' => 'Belgio',
            'Z107' => 'Bolivia',
            'Z108' => 'Brasile',
            'Z109' => 'Bulgaria',
            'Z110' => 'Camerun',
            'Z111' => 'Canada',
            'Z112' => 'Cile',
            'Z113' => 'Cina',
            'Z114' => 'Colombia',
            'Z115' => 'Congo',
            'Z116' => 'Corea del Nord',
            'Z117' => 'Corea del Sud',
            'Z118' => 'Costa Rica',
            'Z119' => 'Cuba',
            'Z120' => 'Danimarca',
            'Z121' => 'Ecuador',
            'Z122' => 'Egitto',
            'Z123' => 'El Salvador',
            'Z124' => 'Etiopia',
            'Z125' => 'Filippine',
            'Z126' => 'Finlandia',
            'Z127' => 'Francia',
            'Z128' => 'Gabon',
            'Z129' => 'Ghana',
            'Z130' => 'Giappone',
            'Z131' => 'Giordania',
            'Z132' => 'Gran Bretagna e Irlanda del Nord',
            'Z133' => 'Grecia',
            'Z134' => 'Guatemala',
            'Z135' => 'Guinea',
            'Z136' => 'Haiti',
            'Z137' => 'Honduras',
            'Z138' => 'India',
            'Z139' => 'Indonesia',
            'Z140' => 'Iran',
            'Z141' => 'Iraq',
            'Z142' => 'Irlanda',
            'Z143' => 'Israele',
            'Z144' => 'Iugoslavia',
            'Z145' => 'Kenya',
            'Z146' => 'Libano',
            'Z147' => 'Libia',
            'Z148' => 'Lussemburgo',
            'Z149' => 'Madagascar',
            'Z150' => 'Marocco',
            'Z151' => 'Messico',
            'Z152' => 'Mozambico',
            'Z153' => 'Nicaragua',
            'Z154' => 'Nigeria',
            'Z155' => 'Norvegia',
            'Z156' => 'Nuova Zelanda',
            'Z157' => 'Paesi Bassi',
            'Z158' => 'Pakistan',
            'Z159' => 'Panama',
            'Z160' => 'Paraguay',
            'Z161' => 'Perù',
            'Z162' => 'Polonia',
            'Z163' => 'Portogallo',
            'Z164' => 'Romania',
            'Z165' => 'Senegal',
            'Z166' => 'Somalia',
            'Z167' => 'Spagna',
            'Z168' => 'Sri Lanka',
            'Z169' => 'Stati Uniti d\'America',
            'Z170' => 'Sudan',
            'Z171' => 'Svezia',
            'Z172' => 'Svizzera',
            'Z173' => 'Tailandia',
            'Z174' => 'Tanzania',
            'Z175' => 'Tunisia',
            'Z176' => 'Turchia',
            'Z177' => 'Uganda',
            'Z178' => 'Uruguay',
            'Z179' => 'Venezuela',
            'Z180' => 'Vietnam',
            'Z181' => 'Congo (Repubblica Democratica)',
            'Z182' => 'Zambia',
            'Z183' => 'Zimbabwe',

            // ── Z200-Z259: Asia e Oceania ─────────────────────────────────
            'Z200' => 'Afghanistan',
            'Z201' => 'Arabia Saudita',
            'Z202' => 'Bahrein',
            'Z203' => 'Bangladesh',
            'Z204' => 'Bhutan',
            'Z205' => 'Birmania (Myanmar)',
            'Z206' => 'Brunei',
            'Z207' => 'Cambogia',
            'Z208' => 'Comore',
            'Z209' => 'Cipro',
            'Z210' => 'Emirati Arabi Uniti',
            'Z211' => 'Figi',
            'Z212' => 'Kuwait',
            'Z213' => 'Laos',
            'Z214' => 'Maldive',
            'Z215' => 'Malaysia',
            'Z216' => 'Mongolia',
            'Z217' => 'Nepal',
            'Z218' => 'Oman',
            'Z219' => 'Papua Nuova Guinea',
            'Z220' => 'Qatar',
            'Z221' => 'Samoa',
            'Z222' => 'Siria',
            'Z223' => 'Singapore',
            'Z224' => 'Tonga',
            'Z225' => 'Yemen',
            'Z226' => 'Kiribati',
            'Z227' => 'Nauru',
            'Z228' => 'Vanuatu',
            'Z229' => 'Tuvalu',
            'Z230' => 'Isole Marshall',
            'Z231' => 'Micronesia',
            'Z232' => 'Palau',
            'Z233' => 'Timor Est',

            // ── Z300-Z399: Africa subsahariana (paesi non in Z100-Z183) ───
            'Z300' => 'Benin',
            'Z301' => 'Botswana',
            'Z302' => 'Burkina Faso',
            'Z303' => 'Burundi',
            'Z304' => 'Capo Verde',
            'Z305' => 'Repubblica Centrafricana',
            'Z306' => 'Ciad',
            'Z307' => 'Costa d\'Avorio',
            'Z308' => 'Gibuti',
            'Z309' => 'Guinea Equatoriale',
            'Z310' => 'Eritrea',
            'Z311' => 'Eswatini',
            'Z312' => 'Gambia',
            'Z313' => 'Guinea-Bissau',
            'Z314' => 'Lesotho',
            'Z315' => 'Liberia',
            'Z316' => 'Malawi',
            'Z317' => 'Mali',
            'Z318' => 'Mauritania',
            'Z319' => 'Mauritius',
            'Z320' => 'Namibia',
            'Z321' => 'Niger',
            'Z322' => 'Ruanda',
            'Z323' => 'São Tomé e Príncipe',
            'Z324' => 'Seychelles',
            'Z325' => 'Sierra Leone',
            'Z326' => 'Togo',
            'Z327' => 'Sudan del Sud',
            'Z328' => 'Comore',

            // ── Z400-Z499: Europa (paesi non in Z100-Z183) ────────────────
            'Z400' => 'Germania',
            'Z401' => 'Ungheria',
            'Z402' => 'Cecoslovacchia',
            'Z403' => 'Repubblica Ceca',
            'Z404' => 'Slovacchia',
            'Z405' => 'Croazia',
            'Z406' => 'Slovenia',
            'Z407' => 'Bosnia ed Erzegovina',
            'Z408' => 'Macedonia del Nord',
            'Z409' => 'Serbia',
            'Z410' => 'Montenegro',
            'Z411' => 'Kosovo',
            'Z412' => 'Moldova',
            'Z413' => 'Ucraina',
            'Z414' => 'Bielorussia',
            'Z415' => 'Estonia',
            'Z416' => 'Lettonia',
            'Z417' => 'Lituania',
            'Z418' => 'Russia',
            'Z419' => 'Armenia',
            'Z420' => 'Azerbaigian',
            'Z421' => 'Georgia',
            'Z422' => 'Kazakistan',
            'Z423' => 'Uzbekistan',
            'Z424' => 'Turkmenistan',
            'Z425' => 'Tagikistan',
            'Z426' => 'Kirghizistan',
            'Z427' => 'Islanda',
            'Z428' => 'Andorra',
            'Z429' => 'Monaco',
            'Z430' => 'San Marino',
            'Z431' => 'Liechtenstein',
            'Z432' => 'Malta',
            'Z433' => 'URSS',

            // ── Z500-Z599: Americhe (paesi non in Z100-Z183) ─────────────
            'Z500' => 'Antigua e Barbuda',
            'Z501' => 'Bahamas',
            'Z502' => 'Barbados',
            'Z503' => 'Belize',
            'Z504' => 'Dominica',
            'Z505' => 'Repubblica Dominicana',
            'Z506' => 'Giamaica',
            'Z507' => 'Grenada',
            'Z508' => 'Guyana',
            'Z509' => 'Saint Kitts e Nevis',
            'Z510' => 'Saint Lucia',
            'Z511' => 'Saint Vincent e Grenadine',
            'Z512' => 'Suriname',
            'Z513' => 'Trinidad e Tobago',
            'Z514' => 'Guyana francese',
        ];
    }
}
